batch_size: 32
epochs: 15
type: "default" # or "vae", "transfer"

optimizer:
  name: adam
  params:
    lr: 0.001
    betas: [0.9, 0.999]

loss:
  name: mse


callbacks:
  - name: print_loss
  - name: early_stopping
    params:
      patience: 5


  - name: checkpoint
    params:
      #directory: checkpoints, for v0
      every_n_epochs: 10
      keep_last: 2
      save_best: true
      monitor: val_loss
      mode: min

num_workers: 1