transform:
  enabled: false
  name: log1p

scaler:
  name: standard
  params:
    with_mean: true
    with_std: true

feature_selection:
  enabled: true
  name: variance_threshold
  params:
    threshold: 0.01

dimensionality:
  enabled: true
  name: pca
  params:
    n_components: 7
    whiten: false



contamination_filter:
  enabled: false