

pointwise:

  scaler:
    enable: true
    name: standard
    params:
      with_mean: true
      with_std: true

  feature_selection:
    enable: false
    name: variance_threshold
    params:
      threshold: 0.01

  dim_reduction:
    enable: true
    name: pca
    params:
      n_components: 4
      whiten: false

  transform:
    enable: false
    name: power
    params:
      method: yeo-johnson

  contamination_filter:
    enabled: false



windowing:
  size: 5
  stride: 1



