


data:
  windowing:
    size:
      choices: [1, 5, 10, 20]


prep:
  scaler:
    names: [standard, minmax]


model_space:
  encoder_dims:
    - name: enc1
      type: int
      low: 16
      high: 64

    - name: enc2
      type: int
      low: 4
      high: 32

  latent_dim:
    name: latent_dim
    type: int
    low: 2
    high: 8

  decoder_dims:
    - name: dec1
      type: int
      low: 16
      high: 64

  beta:
    name: beta
    type: float
    low: 0.1
    high: 2.0




training_space:
  optimizer:
    names: [adam, sgd]

    adam:
      lr:
        low: 1e-4
        high: 1e-2
        log: true

      betas:
        choices:
          - [0.9, 0.999]
          - [0.8, 0.999]

    sgd:
      lr:
        low: 1e-3
        high: 1e-1
        log: true

      momentum:
        low: 0.0
        high: 0.9

      weight_decay:
        low: 1e-6
        high: 1e-2
        log: true


  callbacks:
    print_loss: true

    early_stopping:
      enabled: true
      patience:
        low: 3
        high: 10


  epochs:
    name: epochs
    type: int
    low: 5
    high: 20

  batch_size:
    name: batch_size
    type: categorical
    choices: [32, 64]